"""Per-step widgets for the wizard.

Each module here defines one ``StepBase`` subclass that owns the
content area for that pass. Added in milestones W4 (Calibrate) through
W9 (Tile). Until then this package is empty; the wizard window shows
placeholder widgets generated by ``main_window._make_placeholder_step``.
"""

from .base import StepBase
from .calibrate_step import CalibrateStep
from .validate_labels_step import ValidateLabelsStep
from .validate_fill_step import ValidateFillStep

__all__ = [
    "StepBase",
    "CalibrateStep",
    "ValidateLabelsStep",
    "ValidateFillStep",
]
