"""Per-step widgets for the wizard.

Each module here defines one ``StepBase`` subclass that owns the
content area for that pass. Added in milestones W4 (Calibrate) through
W9 (Tile). Until then this package is empty; the wizard window shows
placeholder widgets generated by ``main_window._make_placeholder_step``.
"""
